kit:
    module_id: "plugin-starter"
build:
    server:
        entries:
            "api/*": "src/server/api/**/*.ts"
            "migrations/*": "src/server/migrations/**/*.ts"
            "seeders/*": "src/server/seeders/**/*.ts"
